# Nmmpy.array的基本操作

In [3]:
import numpy as np

In [14]:
x = np.arange(10)

In [15]:
X = np.arange(15).reshape(3, 5)

## 基本属性

In [16]:
x.ndim

1

In [17]:
X.ndim

2

In [8]:
x.shape

(3, 5)

In [18]:
X.shape

(3, 5)

In [19]:
x.size

10

In [20]:
X.size

15

## numpy.array数据访问

In [ ]:
x
x[0]

In [23]:
x[-1]

9

In [24]:
X[0][0]

0

In [25]:
X[(0, 0)]

0

In [26]:
X[0, 0]

0

注：推荐最后一种方法

In [35]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:

x[0:5]

array([0, 1, 2, 3, 4])

In [29]:
x[:5]

array([0, 1, 2, 3, 4])

In [30]:
x[::2]

array([0, 2, 4, 6, 8])

In [31]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

使用切片的化一定要使用一个中括号这种形式，所以推荐使用这种访问数组

In [38]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

原因：[:2]取前两行形成一个新数组，而[:3]取新数组的前三个元素，也就取了整个新数组

In [39]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [41]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [42]:
X[0]

array([0, 1, 2, 3, 4])

In [43]:
X[0, :]

array([0, 1, 2, 3, 4])

In [44]:
X[:, 0]

array([ 0,  5, 10])

In [52]:
subX 

array([[100,   1,   2],
       [  5,   6,   7]])

In [48]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [49]:
subX[0, 0] = 100

In [50]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [51]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

如果想得到副本，就在后边加copy()

In [52]:
subX 

array([[100,   1,   2],
       [  5,   6,   7]])

In [53]:
subX = X[:2, :3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

### Reshape

In [55]:
x.shape

(10,)

In [56]:
x.ndim

1

In [57]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a = x.reshape(1, 10)

In [61]:
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
a.shape

(1, 10)

In [63]:
x.shape

(10,)

In [64]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [65]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

# 合并操作

In [68]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [70]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [71]:
z = np.array([666, 666, 666])

In [72]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [73]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [74]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [75]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [76]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions

In [77]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [78]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [80]:
B = np.full((2, 2), fill_value=100)

In [81]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [82]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions

# 分割操作

In [83]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.split(x, [3, 7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [86]:
np.split(x, [5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [87]:
A = np.arange(16).reshape(4, 4)

In [88]:
np.split(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [90]:
np.split(A, [2], axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [91]:
np.vsplit(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [93]:
np.hsplit(A,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [94]:
np.hsplit(A, [3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

In [95]:
x, y = np.hsplit(A, [-1])

In [96]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [97]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])