# np.array基础


In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.2'

# Python List 的特点

In [6]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
L[5]

5

In [8]:
L[5] = 100

In [10]:
L[5] = 'machine learning'

In [11]:
import array

In [13]:
arr = array.array('i', [i for i in range(10)])

In [14]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[5]

5

In [16]:
arr[5] = 100

In [17]:
arr[5] = 'machine learning'

TypeError: an integer is required (got type str)

### 注：list速度慢，array无矩阵运算，故用numpy

In [20]:
nparr = np.array([i  for i in range(10)])

In [21]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
nparr[5] = 'Machine Learning'

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [23]:
nparr.dtype

dtype('int64')

In [25]:
nparr[5] = 5.0

In [26]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
nparr.dtype

dtype('int64')

In [29]:
nparr2 = np.array([1, 2, 3.0])

In [30]:
nparr2.dtype

dtype('float64')

# 其他创建np.array的方法

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [37]:
np.ones(shape=(3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
np.full(shape=(3, 5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### arrange

In [40]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [41]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
[i for i in range(0, 20, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [43]:
np.arange(0, 20, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

In [45]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace:第三个参数是元素个数

In [47]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [49]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### np.random 前开后闭区间，第三个参数size是元素个数,可以为元组

In [52]:
np.random.randint(0, 10)

5

In [53]:
np.random.randint(0, 10, 10)

array([9, 9, 1, 8, 6, 3, 0, 7, 3, 5])

In [54]:
np.random.randint(0, 10, size=10)

array([7, 6, 4, 5, 1, 7, 3, 4, 3, 6])

In [55]:
np.random.randint(0, 10, size=(3, 5))

array([[6, 2, 8, 7, 2],
       [2, 7, 4, 4, 1],
       [9, 5, 1, 8, 6]])

In [56]:
np.random.seed(666)

In [57]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [62]:
np.random.seed(666)
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [63]:
np.random.random()

0.7315955468480113

In [65]:
np.random.random((3, 5))

array([[0.26832981, 0.75366384, 0.66673747, 0.87287954, 0.52109719],
       [0.75020425, 0.32940234, 0.29130197, 0.00103619, 0.6361797 ],
       [0.97933558, 0.91236279, 0.39925165, 0.40322917, 0.33454934]])

In [67]:
np.random.normal()

0.3139856301975447

In [68]:
np.random.normal(10, 100)

49.63856739415942

In [69]:
np.random.normal(10, 100, (3, 5))

array([[  67.65658375,    2.98059308,  101.25043617,  110.4704966 ,
          51.85992895],
       [-142.90245423,  102.48753198,   28.3054285 ,   44.54349606,
         -71.31543023],
       [ 116.32538229,   35.8663847 ,   57.28510669,  113.19697961,
          -6.0456546 ]])

In [73]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap