In [2]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
x[3]

3

In [4]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [6]:
ind = [3, 5, 8]
x[ind]

array([3, 5, 8])

In [8]:
ind = np.array([[0, 2], [1, 3]])

In [9]:
x[ind]

array([[0, 2],
       [1, 3]])

In [12]:
x = x.reshape(4, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
x[row, col]

array([ 1,  6, 11])

In [15]:
x[0, col]

array([1, 2, 3])

In [17]:
x[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [18]:
col = [True, False, True, True]
x[:3, col]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

# numpy.array 的比较

In [19]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
x < 3

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
x <= 3

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
np.sum(x <= 3)

4

In [25]:
np.any(x ==0)

True

In [27]:
np.all(x >= 0)

True

In [28]:
np.sum(x % 2 == 0)

8

In [29]:
np.sum(x % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [31]:
np.all(x > 0, axis=0)

array([False,  True,  True,  True])

#### 与或非

In [32]:
np.sum((x > 3) & (x < 10))

6

In [33]:
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (<ipython-input-33-d834f65999a2>, line 1)

In [34]:
np.sum((x % 2 == 0) | (x > 10))

11

In [35]:
np.sum(~(x == 0))

15

#### 抽出一部分数据

In [36]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [37]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [38]:
x[x[:, 3] % 3 == 0]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])