#测试算法

In [4]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [5]:
iris = datasets.load_iris()

In [54]:
x = iris.data
y = iris.target

In [55]:
x.shape

(150, 4)

In [56]:
y.shape

(150,)

# train_test_split

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

np.random.permutation（x）：随机索引，对x数值以内的所有值，也就是0-（x-1）随机排列

In [12]:
shuffle_indexes = np.random.permutation(len(x))

In [13]:
shuffle_indexes

array([ 52,   1,  49,  98,  15, 132,  63, 140, 102,  37,   9, 113, 133,
       112,  93,  74, 137, 149, 115,   6, 124,   3,  14,  97,  12,  36,
        26,  91,  88,  38, 119,  90,  11, 138,  20,  73, 116,  27, 120,
       142, 141, 136, 106,  57, 123,  84,  30, 129,  31,  70, 101,  50,
       135,  76,  61,  24, 110,  22,  28, 147,  99,   5,  19,  25,  41,
        85,  60, 127, 100,  67,  81,  77,  69,  16,  55,  66, 114,  62,
        40,   2, 121, 103,  17,  71,  64,   7, 144,  51, 107,  87,  82,
        35, 145,  78,  94, 105,  13, 104, 125,  29,  23,  79,  54,   4,
        53,  45,  18,  33,  80,   0, 146,  43,  39, 143, 148,  44,  65,
       139,  56,  58,  21,  83, 118,  47, 109, 122,  34,  10, 108,   8,
        92,  72, 117, 111,  95, 130,  59,  68,  48,  75,  32,  42, 131,
       134, 128,  86, 126,  96,  89,  46])

In [15]:
test_ratio = 0.2
test_size = int(len(x)*0.2)

In [16]:
test_size

30

In [17]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [18]:
x_train = x[train_indexes]
y_train = y[train_indexes]
x_test = x[test_indexes]
y_test = y[test_indexes]

In [19]:
x_test.shape

(30, 4)

In [20]:
y_test

array([1, 0, 0, 1, 0, 2, 1, 2, 2, 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 2, 0,
       0, 1, 0, 0, 0, 1, 1, 0])

In [21]:
from collections import Counter

In [28]:
Counter(y_test)

Counter({0: 12, 1: 8, 2: 10})

#自己的数据划分算法，未分层

In [36]:
%run /home/lds/code/machine-learning/study/KNN/model_selection.py

In [38]:
train_test_split(x, y)

(array([[5.7, 3. , 4.2, 1.2],
        [5.2, 2.7, 3.9, 1.4],
        [5.9, 3. , 4.2, 1.5],
        [5.4, 3.9, 1.3, 0.4],
        [6.2, 2.9, 4.3, 1.3],
        [4.6, 3.4, 1.4, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [7.2, 3. , 5.8, 1.6],
        [5.1, 3.5, 1.4, 0.3],
        [6.3, 2.5, 4.9, 1.5],
        [5.8, 2.6, 4. , 1.2],
        [4.8, 3. , 1.4, 0.3],
        [5. , 3.5, 1.6, 0.6],
        [6.7, 3. , 5. , 1.7],
        [6.4, 3.1, 5.5, 1.8],
        [5.6, 2.7, 4.2, 1.3],
        [5.3, 3.7, 1.5, 0.2],
        [5.9, 3.2, 4.8, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [4.9, 3.1, 1.5, 0.1],
        [5.8, 2.7, 5.1, 1.9],
        [6.3, 3.3, 6. , 2.5],
        [5.7, 4.4, 1.5, 0.4],
        [6.3, 3.4, 5.6, 2.4],
        [5.9, 3. , 5.1, 1.8],
        [6.5, 3. , 5.5, 1.8],
        [5.7, 2.8, 4.1, 1.3],
        [5.7, 2.5, 5. , 2. ],
        [5.2, 4.1, 1.5, 0.1],
        [6.3, 2.3, 4.4, 1.3],
        [7.3, 2.9, 6.3, 1.8],
        [5.7, 2.8, 4.5, 1.3],
        [6.8, 3. , 5.5, 2.1],
        [7

In [40]:
x_train,y_train,x_test,y_test= train_test_split(x, y)

In [41]:
x_train.shape

(120, 4)

In [43]:
y_train.shape

(120,)

# sklearn split

In [2]:
from sklearn.model_selection import train_test_split

In [49]:
x_train,x_test,y_train,y_test= train_test_split(x, y, test_size=0.2)

In [50]:
y_train

array([0, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1, 2, 2, 0, 1, 0, 1, 1, 2, 0, 2, 1,
       1, 1, 2, 2, 2, 2, 0, 2, 1, 2, 1, 1, 0, 2, 2, 0, 0, 1, 2, 2, 0, 2,
       2, 0, 2, 0, 0, 1, 1, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1, 2, 0, 2, 2,
       2, 2, 1, 1, 2, 1, 2, 1, 0, 1, 0, 1, 2, 1, 2, 0, 1, 2, 2, 2, 2, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 2, 2, 0, 0, 1, 1, 2, 2, 0,
       0, 2, 1, 2, 1, 1, 0, 1, 1, 1])

In [51]:
Counter(y_train)

Counter({0: 36, 1: 44, 2: 40})

# 分层采样

In [11]:
v = x
w = y

train_test_split()参数
X:
y:
test_size：比例
train_size：比例
stratify：默认None，可指定一个数组分层采样
random_state：随机种子
shuffle:stratify为None时，shuffle必须为false

In [13]:
x_train,x_test,y_train,y_test= train_test_split(v, w, test_size=0.2, stratify=y)

In [16]:
from collections import  Counter
Counter(y)

Counter({0: 50, 1: 50, 2: 50})

# 交叉验证

### 直接计算某个已确定参数的模型其交叉验证分数的方法

In [21]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

In [50]:
X,Y = datasets.load_breast_cancer(return_X_y=True)

In [51]:
clf = KNeighborsClassifier(n_neighbors=6)

In [52]:
score = cross_val_score(clf, X, Y, cv=5, scoring="accuracy")

In [39]:
print('accuracy:'+str(score)+'\n')

accuracy:[0.89565217 0.93913043 0.9380531  0.92920354 0.92035398]



In [53]:
score = cross_val_score(clf, X, Y, cv=5, scoring="f1")
score

array([0.92105263, 0.95238095, 0.95104895, 0.94366197, 0.9352518 ])

返回多个评分标准的交叉验证方法

In [27]:
from sklearn.model_selection import cross_validate

In [46]:
X, Y = datasets.load_breast_cancer(return_X_y=True)

In [31]:
scoring = ['accuracy','f1']

In [48]:
core = cross_validate(clf,X,Y,scoring=scoring,cv=5,return_train_score=True)

In [49]:
core

{'fit_time': array([0.00444818, 0.00063372, 0.00058126, 0.00057387, 0.00074887]),
 'score_time': array([0.01315928, 0.00350475, 0.00310373, 0.00299096, 0.00281525]),
 'test_accuracy': array([0.89565217, 0.93913043, 0.9380531 , 0.92920354, 0.92035398]),
 'test_f1': array([0.92105263, 0.95238095, 0.95104895, 0.94366197, 0.9352518 ]),
 'train_accuracy': array([0.94933921, 0.94493392, 0.93859649, 0.93421053, 0.94517544]),
 'train_f1': array([0.96      , 0.95636998, 0.95121951, 0.94755245, 0.95652174])}

### 生成数据集的交叉验证法

KFold() 生成器的方式产出每一次交叉验证所需要的训练集和验证集
    n_splits:int型，控制k折交叉验证中的k，默认为3
    shuffle:bool型，是否在采样前打乱原数据顺序
    random_state: 随机种子
    方法：split（） 返回：train, test的对应索引
          get_n_splits() 返回 k值

注：不是分层采样
see also : StratifiedKFold() 分层采样，交叉验证
           GroupKFold（） 

In [42]:
from sklearn.model_selection import KFold

In [57]:
kf = KFold(n_splits=5)


In [72]:
for train, test in kf.split(x):
    print(train, '\n', test)

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149] 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132

In [64]:
from sklearn.model_selection import StratifiedKFold

In [65]:
skf = StratifiedKFold(n_splits=5)

In [66]:
skf.get_n_splits(X)

5

In [73]:
print(Counter(Y))
for train, test in skf.split(X, Y):
    train_y = Y[train]
    print(Counter(train_y))

Counter({1: 357, 0: 212})
Counter({1: 285, 0: 169})
Counter({1: 285, 0: 169})
Counter({1: 286, 0: 170})
Counter({1: 286, 0: 170})
Counter({1: 286, 0: 170})


其他数据划分方法：
    留一法：LeaveOneOut()
    留出法：LeavePOut()
    时间序列的数据划分法：TimeSeriesSplit（）