# 聚合操作

In [4]:
import numpy as np

In [12]:
L = np.random.random(1000000)

In [13]:
%time
sum(L)

CPU times: user 9 µs, sys: 0 ns, total: 9 µs
Wall time: 14.8 µs


500348.6270017652

In [14]:
%time
np.sum(L)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.77 µs


500348.62700173305

In [15]:
np.min(L)

5.099058379975929e-07

In [17]:
np.max(L)

0.9999999948294409

In [18]:
L.max()

0.9999999948294409

In [19]:
L.min()

5.099058379975929e-07

In [20]:
x = np.arange(16).reshape(4,-1)

In [21]:
np.sum(x)

120

In [22]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.sum(x, axis=1)

array([ 6, 22, 38, 54])

In [24]:
np.sum(x, axis=0)

array([24, 28, 32, 36])

累乘

In [25]:
np.prod(x)

0

均值

In [27]:
np.mean(x)

7.5

中位数

In [28]:
np.median(x)

7.5

百分位数：它使得至少有p%的数据项小于或等于这个值，且至少有(100-p)%的数据项大于或等于这个值。
50%的分位数，就是x里排序之后的中位数.
numpy.percentile
Parameters
    ----------
    a : np数组
    q : float in range of [0,100] (or sequence of floats)
        Percentile to compute。
        要计算的q分位数。
    axis : 那个轴上运算。
    keepdims :bool是否保持维度不变。
----------------

In [29]:
np.percentile(x, q=50)

7.5

In [30]:
for percentile in [0, 25, 50, 75, 100]:
    print(np.percentile(x, q=percentile))

0.0
3.75
7.5
11.25
15.0


方差

In [31]:
np.var(x)

21.25

标准差

In [32]:
np.std(x)

4.6097722286464435

In [34]:
x = np.random.normal(0, 1, size=1000000)

In [35]:
np.mean(x)

-0.0016608118768103072

In [36]:
np.std(x)

0.999978854658203

# 索引

In [37]:
np.min(x)

-4.791894570747705

In [38]:
np.argmin(x)

816465

In [39]:
x[np.argmin(x)]

-4.791894570747705

In [41]:
np.argmax(x)

514604

### 排序和使用索引

In [42]:
x = np.arange(16)

把x顺序打乱

In [43]:
np.random.shuffle(x)
x

array([ 3,  6,  1,  9,  2,  4, 13, 12, 15, 11,  5,  0, 10,  7, 14,  8])

np.sort(x)不改变x的顺序，要改变则要用x.sort()

In [44]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
x

array([ 3,  6,  1,  9,  2,  4, 13, 12, 15, 11,  5,  0, 10,  7, 14,  8])

In [46]:
x.sort()

In [47]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
x = np.random.randint(10, size=(4, 4))

In [49]:
x

array([[2, 1, 8, 1],
       [0, 6, 7, 9],
       [1, 2, 5, 2],
       [0, 8, 4, 3]])

In [51]:
np.sort(x)

array([[1, 1, 2, 8],
       [0, 6, 7, 9],
       [1, 2, 2, 5],
       [0, 3, 4, 8]])

In [52]:
np.sort(x, axis=0)

array([[0, 1, 4, 1],
       [0, 2, 5, 2],
       [1, 6, 7, 3],
       [2, 8, 8, 9]])

In [53]:
x

array([[2, 1, 8, 1],
       [0, 6, 7, 9],
       [1, 2, 5, 2],
       [0, 8, 4, 3]])

In [54]:
x = np.arange(16)

In [55]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
np.random.shuffle(x)

In [58]:
x

array([ 7,  4, 14,  2,  0,  6,  1, 11,  8, 12, 15, 10,  5,  9, 13,  3])

In [59]:
np.argsort(x)

array([ 4,  6,  3, 15,  1, 12,  5,  0,  8, 13, 11,  7,  9, 14,  2, 10])

快速排序partition操作,标杆
第一个参数是数组，第二个参数是标杆数值

In [64]:
x

array([ 7,  4, 14,  2,  0,  6,  1, 11,  8, 12, 15, 10,  5,  9, 13,  3])

In [63]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  6,  5,  7,  8, 12, 15, 10, 14,  9, 13, 11])

In [66]:
np.argpartition(x, 3)

array([ 4,  6,  3, 15,  1,  5, 12,  0,  8,  9, 10, 11,  2, 13, 14,  7])

In [67]:
X = np.arange(16).reshape(4, 4)

In [76]:
np.random.shuffle(X)
X

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
np.argsort(X)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [78]:
np.argsort(X, axis=0)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [0, 0, 0, 0]])